### ISSUE TITLE
[Bug]: Chording doesn't work properly

### ISSUE THREAD

**Issue by putianyi889** [Journeyman-dev/FossSweeper#30]
### Bug Description

Chording doesn't work correctly.

### Expected Behaviour

Chording only works when the cell is opened and the adjacent flags match the number.

### Observed Behaviour

Chording always open 9 cells.

By the way, x86 refers to 32-bit while x64 refers to 64-bit, in this issue template. Also, the `CODE_OF_CONDUCT.md` should be in the `issues` folder.

### FossSweeper Version

0.2.0

### Operating System

Windows 10

### System Configuration

64 bit (x86)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by Journeyman-dev** [comment]
Good point with the configurations, I will fix that shortly. CODE_OF_CONDUCT.md is fine where it is I think according to https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

**Comment by putianyi889** [comment]
The link in the issue template does point to `issues/CODE_OF_CONDUCT.md`.

**Comment by Journeyman-dev** [comment]
> The link in the issue template does point to `issues/CODE_OF_CONDUCT.md`.

Pulling a fix to this now, thank you for telling me.

I am going to work on the chording bug after I finish all other issues. I think I need to refactor how I have the application layed out a bit. Determining what to do in with various mouse inputs within the desktop_view model is turning out to be a mess, and it is also not unit testable. I am going to create a new module "fsweep_controller" which manages all of this stuff.
