### ISSUE TITLE
chording doesn't work correctly

### ISSUE THREAD

**Issue by putianyi889** [Journeyman-dev/FossSweeper#60]
### Bug Description

.

### Expected Behaviour

After releasing one key from chord, holding the other key and press the first key again should trigger another chord.

### Observed Behaviour

The second chord only works after releasing both keys from the first chord.

### FossSweeper Version

0.4.0

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by Journeyman-dev** [comment]
I will fix this shortly.  I need to move the mouse button state and position into the model in order to make it testable.

**Comment by ralokt** [comment]
perhaps unsurprisingly, this is also an issue on linux!

**Comment by Journeyman-dev** [comment]
I'm doing a quick fix for now, will do the input model changes after this.
