### ISSUE TITLE
Drag cursor out of the window

### ISSUE THREAD

**Issue by putianyi889** [Journeyman-dev/FossSweeper#76]
### Bug Description

If the key is released out of the window, the event should be captured.

### Expected Behaviour

Press left in the window, drag out and release left, then move the cursor back in, and the cursor should be in the initial state.

### Observed Behaviour

Press left in the window, drag out and release left, then move the cursor back in, and it's still in the pressed state.

### FossSweeper Version

0.5.0

### FossSweeper Hash

#45c45fc

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by Journeyman-dev** [comment]
Actually, I don't see this myself. Maybe this is windows only, I will check.

**Comment by Journeyman-dev** [comment]
I compiled and ran on Windows and I have this same issue. I didn't notice it on the Linux distribution that I normally use. I will forward this report to wxWidgets.

**Comment by Journeyman-dev** [comment]
A solution has been found. Pulling it now.
