### ISSUE TITLE
Chording when right up first doesn't work

### ISSUE THREAD

**Issue by putianyi889** [Journeyman-dev/FossSweeper#88]
### Steps

1. Find a number with proper flags around
2. Press right and left and move cursor to the number
3. Release right

### Expected Behaviour

Chording should be triggered.

### Observed Behaviour

Chording doesn't take effect.

### FossSweeper Version

1.0.0

### FossSweeper Hash

5a10577

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by Journeyman-dev** [comment]
Pulling a fix now.
